services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker_appdata:/app/data
      - /mnt/data/Dockering:/mnt/data/Dockering
    environment:
      - DOCKGE_STACKS_DIR=/mnt/data/Dockering
    networks:
      - public_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.docker.rule=Host(`docker.mouaad-ops.me`)
      - traefik.http.routers.docker.entrypoints=web
      - traefik.http.routers.docker.service=docker-web-svc
      - traefik.http.services.docker-web-svc.loadbalancer.server.port=5001
networks:
  public_network:
    external: true
volumes:
  docker_appdata:
    driver: local
